version: '3'

services:
  django:
    build: .
    command: sh -c "../entrypoint.sh"
    volumes:
      - django_storage:/usr/src/django
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_TIME_ZONE: ${DJANGO_TIME_ZONE}
      DJANGO_PORT: ${DJANGO_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_storage:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always

  celery-worker:
    build: .
    restart: always
    command: celery -A api worker -l info
    volumes:
      - django_storage:/usr/src/django
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - django

  celery-beat:
    build: .
    restart: always
    command: celery -A api beat -l info
    volumes:
      - django_storage:/usr/src/django
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - django

volumes:
  mysql_storage:
  django_storage:
