version: '3'

services:
  web:
    build: .
    command: sh -c "../entrypoint.sh"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ra-delta-db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super-secret
      MYSQL_DATABASE: ra-delta-db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_storage:/var/lib/mysql

volumes:
  mysql_storage: